print("hi")
print(2+3)
print(5-1)
print(1-5)
print(3*4)
print(8/2) 
print(7//3)
print(7%3)
print(2**3)
print((2+3)*4) 
print(type(1))
print(type(1.5))
print(type("hello"))   
print(type(True))
print(type(2j))
print(1 < 2)
print(type([1, 2, 3]))
print(type({'fasa':"asdas"}))
print(type((1, 2, 3)))
print(type({1, 2, 3}))
x="an"
print(x)
a=["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","b","f"]
print(a)
print(a[0])
print(a[0:9])
print(a[::2])#intervals 
print(a[0:9:3])#intervals
print(a[::-1])#reverse
print(a[0:9:1])
for i in a:
    print(i)
#print(dir(a))
#print(help(a))
print(len(a))
print("c"in a)
b=1
while b<10:
    print("fuck")
    b=b+1
for i in a:
    print(i)
a.append("p")
print(a)
a.remove("a")
print(a)
a.insert(14,"z")
print(a)
a.sort()
print(a)
n=[3,1,4,2,5]
n.sort()
print(n)
n.reverse()
print(n)
n.clear()
print(n) 
print(a.index("c"))
print(a.count("b"))
print(a.count("g"))
y={"a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","b","f"}
print(y)
for i in y:
    print(i)
y.add("p")
print(y)
y.remove("p")
print(y)
y.pop()
print(y)
y.add("a")
print(y)
y.clear()
print(y)
z=(1,2,3,4,5,6,7,8,9,10,1,2,3)
print(z)
print(z[0])
print(len(z))
print(z.index(2))
print(z.count(3))
for i in z:
    print(i)
